name: Static Analysis Trigger

on:
  pull_request:
    branches: [develop]
    
jobs:
  save-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Persist branch name
        run: |
          mkdir -p ./pr
          echo "${{ GITHUB_HEAD_REF }}" > ./pr/branch.txt
      - name: Upload branch name
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/